### ISSUE TITLE
dev container doesn't automatically install any of the tools necessary to setup/start my project...

### ISSUE THREAD

**Issue by Mr0cket** [docker/dev-environments#102]
**Tell us about your request**
My project uses lots of cli tools,  necessary to setup & start it... e.g: `node` The dev container does not come with any of these tools, nor at the correct versions... it's useless. I can create a better container myself that has all the tools I need in 5 mins.

**Which service(s) is this request for?**
dev Environments

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I want to be able to setup and run my project **easily** in a container using dev environments. Currently the dev environments container does not detect and install any of the essential tools I need to do anything with my project. So what's the point of it?? I can create a container optimised for my project with all tools already installed in basically the same time...

**Are you currently working around the issue?**
not using dev environments

**Comment by glours** [comment]
Hello @Mr0cket 

Can you share the log of you dev environment startup (without using your image)
Dev Environments currently detect and provide base images for Javascript, Go, Java and Ruby projects

**Comment by Mr0cket** [comment]
Hi, My dev environment is a node/typescript client/server project, here are the logs for environment startup:

```
Preparing to clone inside a volume
Installing credential helpers... done
Cloning into '/code'...
remote: Enumerating objects: 17785, done.
remote: Counting objects: 100% (252/252), done.
remote: Compressing objects: 100% (155/155), done.
remote: Total 17785 (delta 136), reused 162 (delta 77), pack-reused 17533
Receiving objects: 100% (17785/17785), 228.30 MiB | 6.33 MiB/s, done.
Resolving deltas: 100% (11636/11636), done.
Updating files: 100% (826/826), done.
Detecting main repo language...
Detected 'TypeScript' as the main repository language.
Docker socket permission set to allow in container docker
``` 

The dev container used is: `dev-environments-default:stable-1`.

**Comment by glours** [comment]
Thanks, the issue is fixed (we didn't detect TypeScript as Javascript project) and should be release in the next Docker Desktop version.
As a work around you can add a `.docker/config.json` file in your repo with the following content
```
{
  "image": "docker/dev-environments-javascript:stable-1"
}
```
