### ISSUE TITLE
When running the sample single container dev environment I get no such image docker/desktop-git-helper

### ISSUE THREAD

**Issue by tetrode** [docker/dev-environments#105]
**Describe the bug**
When running the sample single container dev environment I get no such image docker/desktop-git-helper:5a4fca126aadcd3f6cc3a011aa991de982ae7000

**To Reproduce**
1. Run docker 4.6.0 (75818)
2. Click on Dev Environments, single container dev environment
3. At the setup, use the proposed https://github.com/dockersamples/single-dev-env repo
4. Error message

Preparing to clone inside a volume
Installing credential helpers... done
Cloning into '/code'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 14 (delta 3), reused 9 (delta 1), pack-reused 0
Receiving objects: 100% (14/14), 6.93 KiB | 6.93 MiB/s, done.
Resolving deltas: 100% (3/3), done.
Error response from daemon: No such image: docker/desktop-git-helper:5a4fca126aadcd3f6cc3a011aa991de982ae7000

**Expected behavior**
A new dev environment to work with...

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Monterey 12.3

**Version of Docker Desktop:**  
You can find the version by clicking on the `About Docker Desktop` menu
```
Docker 4.6.0 (75818)
Engine: 20.10.13
Compose: v2.3.3
Credential Helper: 0.6.4
Kubernetes: v1.22.5
Snyk: v1.827.0
```

**Additional context**

**Comment by glours** [comment]
@tetrode did you try to pull it manually and then retry? 
`docker pull docker/desktop-git-helper:5a4fca126aadcd3f6cc3a011aa991de982ae7000`

**Comment by tetrode** [comment]
That takes me already steps further, I now get

Preparing to clone inside a volume
Installing credential helpers... done
Cloning into '/code'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 14 (delta 3), reused 9 (delta 1), pack-reused 0
Receiving objects: 100% (14/14), 6.93 KiB | 2.31 MiB/s, done.
Resolving deltas: 100% (3/3), done.
Downloading tool to detect main repo language...
Done downloading.
Detecting main repo language...
Detected 'Go' as the main repository language.
Docker socket permission set to allow in container docker

I now have a container named single-dev-env-funny-name but it is stopped and I had some issues to start it. It is starting now, issue solved, thanks

**Comment by glours** [comment]
Can we close the issue?

**Comment by tetrode** [comment]
Yes you can close the issue, thanks
