### ISSUE TITLE
Specify branch when cloning

### ISSUE THREAD

**Issue by Dids** [docker/dev-environments#11]
**Tell us about your request**
Add the ability to specify or select a branch when creating a new Dev Environment from a git repository.

**Which service(s) is this request for?**
Docker Desktop's Dev Environments.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
For most of the projects I work on, I would need to specify a branch when cloning/creating a Dev Environment from a git repo, and from what I can tell this is currently not possible with Dev Environments.

**Are you currently working around the issue?**
No, as I'm not aware of any workarounds.

**Comment by rumpl** [comment]
Hey @Dids thanks for opening this issue, we are working on this in this sprint so it will be available in the next release.

Fun fact: we had this feature but it got lost in a refactoring

👍

**Comment by gtardif** [comment]
Hi @Dids that should be in next release, you will be able to add `@mybranch` suffix in git urls

**Comment by glours** [comment]
@Dids we just release the new version of Docker Desktop, can you check if everything works as expected now? 
You can update the version by clicking on the `Check for Updates` menu in DD

**Comment by glours** [comment]
@Dids that's ok, no worries 😉

**Comment by Hronom** [comment]
Hey sorry, but did you lost this feature again? I can't find it. I try to clone private repository using ssh
