### ISSUE TITLE
Unable to create sample Dev Environments

### ISSUE THREAD

**Issue by usha-mandya** [docker/dev-environments#12]
**Describe the bug**
Unable to create sample Dev Environments from `git@github.com:dockersamples/single-dev-env.git` and `git@github.com:dockersamples/compose-dev-env.git` Git repositories on Docker Desktop version 3.5.1 (build 66090).

**To Reproduce**
1. Add the Git URL `git@github.com:dockersamples/compose-dev-env.git` in the Create field
2. Click Create
3. This gives the following error
  ![image](https://user-images.githubusercontent.com/47779042/123651999-d392cb80-d823-11eb-88f0-3b9dedf09d09.png)
4. However, when you click 'Start', it displays a message indicating that the image is being pulled but creates the dev environment with only one container
 ![image](https://user-images.githubusercontent.com/47779042/123652265-0b9a0e80-d824-11eb-9d5e-79fa00481ee0.png)

**Expected behavior**
I was expecting to see the Compose Dev Environment with multiple services similar to 

  ![image](https://user-images.githubusercontent.com/47779042/123652806-882ced00-d824-11eb-8855-98c8afedb292.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Version: 11.4

**Additional context**

**Comment by rumpl** [comment]
Thanks @usha-mandya 

Can you please follow the instructions here to upload a diagnostics report: https://docs.docker.com/docker-for-mac/troubleshoot/#diagnose-and-feedback

Could you also show us the logs of the created environment: click on the environment and a popup should open with the logs

Thanks

**Comment by usha-mandya** [comment]
Sure @rumpl . Will upload the diagnostics. Meanwhile, here's a screenshot of the logs

![image](https://user-images.githubusercontent.com/47779042/123654245-c971cc80-d825-11eb-9147-7d48d53b4b5b.png)

**Comment by usha-mandya** [comment]
Uploaded the diagnostics. Here's the ID - BE9AFAAF-F68B-41D0-9D12-84760E6B8740/20210628143152

**Comment by usha-mandya** [comment]
Thank you @rumpl. That Adding the SSH to the ssh-agent worked.

![image](https://user-images.githubusercontent.com/47779042/123655951-608b5400-d827-11eb-8c70-69c7ead8558f.png)

**Comment by usha-mandya** [comment]
@rumpl Here's the PR to update docs -  https://github.com/docker/docker.github.io/pull/13081. PTAL

**Comment by glours** [comment]
@usha-mandya can we close this issue?
