### ISSUE TITLE
I can't push commits to Github remote repository

### ISSUE THREAD

**Issue by AbderrazzakB** [docker/dev-environments#127]
I can't push commits to the remote repository

**To Reproduce**
1. Create a dev container following the steps in the docker desktop app from a remote GitHub repository
2. Update some files
3. Commit updates

**Expected behavior**
Push commits to Github remote repository 

**Screenshots**
![image](https://user-images.githubusercontent.com/23277063/180081106-0f5f661f-c2b4-4953-91fa-ca86d09beb9e.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10, WSL 2]

**Version of Docker Desktop:**  
4.10.1
```
(warning: url has no scheme: helperselector
fatal: credential url cannot be parsed: helperselector)
```

**Comment by glours** [comment]
Can you try [this](https://github.com/desktop/desktop/issues/9597#issuecomment-617810468)? It seams to be a specific issue of Git for Windows and not related to Docker Dev Environments

**Comment by AbderrazzakB** [comment]
Thank you, it worked
for me, I had to remove the helper config from the .gitconfig file, the command didn't work for me!
