### ISSUE TITLE
Debugging Dev Environments Locally

### ISSUE THREAD

**Issue by qnm** [docker/dev-environments#14]
**Tell us about your request**
I have a repository which I wish to run as a 'Dev Environment'. I have added the original `docker-compose.yaml` to the `.docker` directory, however I receive an `Invalid template:` error when I add this repo to Dev Environments in Docker Desktop.

Modifying the master branch on a repo to debug is dangerous and inefficient. I could potentially fork the repo, but this also seems inefficient.

How can I execute the Dev Environment locally to debug the issue?

**Which service(s) is this request for?**
Dev Environments.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I wish to run one of my existing docker-compose repos as a Dev Environment.

**Are you currently working around the issue?**
No.

**Comment by nebuk89** [comment]
Hey @qnm if you fancy giving us some direct feedback or chatting to the team on a call drop me an email on bengotch@docker.com :D

**Comment by glours** [comment]
@qnm you can now run a Dev Environments from a local repo with `3.6.0` version of Docker Desktop, just click on the `Check for Updates` menu to install it.
You should be able to start a [local version of your repo](https://docs.docker.com/desktop/dev-environments/#start-a-dev-environment-from-a-local-folder) or you can also [checkout a specific branch/tag](https://docs.docker.com/desktop/dev-environments/#create-a-dev-environment-from-a-specific-branch-or-tag) of your remote repo

**Comment by glours** [comment]
Hello @qnm 
Did you had time to check if this issue is resolve or not?

Can we close the ticket?
