### ISSUE TITLE
cant create container if there is a dot in the git url

### ISSUE THREAD

**Issue by SHenry07** [docker/dev-environments#17]
**Describe the bug**
cant create container if there is a dot in the git url.
Like: http://gitlab.com/Firstname.Lastname/XXXX.git
> When a new user is created in Active Directory, the Full name field is always generated in FirstName LastName format.

**To Reproduce**
1. create a user that username is mail style(Firstname.Lastname)
2. create a repo

**Expected behavior**
Like `git clone`, support all git url 

**Desktop (please complete the following information):**
 - OS: window
 - Version: 10

**Additional context**
[What is a valid email address?](http://isemail.info/about)

**Comment by rumpl** [comment]
Hello @SHenry07 nice catch! We will definitely fix this quickly.

Thanks

**Comment by glours** [comment]
Hello @SHenry07 
We just released new version of Docker Desktop and this issue should be solved in this release.
Can you update by clicking on the `Check for Updates` menu and check that we can close this issue?

**Comment by SHenry07** [comment]
late reply. Now docker-desktop work well for me.
