### ISSUE TITLE
Windows Git always need to install

### ISSUE THREAD

**Issue by diwangtseb** [docker/dev-environments#24]
**Describe the bug**

**To Reproduce**
1.
![image](https://user-images.githubusercontent.com/52818250/124573877-84c8df80-de7c-11eb-9fb3-aa9d5ed920c8.png)
2. 
![image](https://user-images.githubusercontent.com/52818250/124573936-93af9200-de7c-11eb-821c-d1a29e359aec.png)
3. wsl docker-compose can't shut down
![image](https://user-images.githubusercontent.com/52818250/124574219-d70a0080-de7c-11eb-8cb3-bfffd5633cd2.png)

i want to konw how can i solve these problems，thanks！

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Docker version 20.10.7, build f0df350

**Additional context**

**Comment by rumpl** [comment]
Hey @diwangtseb 

I'm not sure I understand the point `3.`, at what point do you get this error?

As for git, I see you are in `c:\users\administrator` is that a shell you opened as admin? Do you have git wit a "normal" user shell (or powershell)?

**Comment by diwangtseb** [comment]
@rumpl 
Thank you for your answer which is indeed a question of authority，admin is normal 😅

**Comment by diwangtseb** [comment]
3. wsl docker-compose can't shut down  
![image](https://user-images.githubusercontent.com/52818250/124579901-29015500-de82-11eb-8508-ab30def777a5.png)
But I still have this problem, when I choose to stop, I get an error, but the previous version didn't，what should i do ?

**Comment by rumpl** [comment]
Thanks, the error you have is not related to dev environments, it's best you open an issue for the docker-compose error here: https://github.com/docker/for-win/issues

**Comment by diwangtseb** [comment]
@rumpl  ok!
