### ISSUE TITLE
How to reinstall environments

### ISSUE THREAD

**Issue by nvthuong1996** [docker/dev-environments#26]
If use vscode remote container extension, all config define in .devcontainer folder.
If config change vscode will waring rebuild image and reload window.

i start use Docker Development Environments by clone 1 project git. If project does not have enough environments how can i add config and rebuild Development Environments. for example i want to add mysql docker, ... etc.
If you have to have a full configuration before creating "Docker Development Environments", it's inconvenient

I have read the documentation many times but really I don't fully understand how "Docker Development Environments" works.

**Comment by alantbarlow** [comment]
It's hard to tell what feature is being requested here but it sounds like you are requesting a feature to have Dev Environments monitor your connected Repo and rebuild images if necessary.

Currently, when pushing changes to your Dockerfile/docker-compose.yaml files, you would need to create a new environment to see the effects.

The requested feature would be to monitor those files and rebuild the environment when there are changes. This could take a lot of work if it's even possible. Another possible solution could be to add a rebuild button on the container group. Once pressed it'll then reclone the connected repository and rebuild all its containers.

**Comment by nvthuong1996** [comment]
thank you. i understand
