### ISSUE TITLE
Dev Environments: Error on OPEN IN VSCODE

### ISSUE THREAD

**Issue by lutaiphong** [docker/dev-environments#28]
While trying Dev Environments feature, I got a bug when I click "OPEN IN VSCODE" button, it shows an error as in screenshot.

1. Open Docker Desktop
2. Choose "Dev Environments (Preview)"
3. Click "Compose bases dev environment"
4. Wait for docker-compose finishes
5. Click "OPEN IN VSCODE" button on any container

Expected behavior
- VScode is opened with the code from the container.

Screenshots
![image](https://user-images.githubusercontent.com/3783241/125560233-8dfd0235-ae7c-4c53-a0eb-3dae6e2e299b.png)

System
 - Windows 10 21H1 (OS build 19043.1110) 64-bit
- Docker Desktop 3.5.2
- Windows Username: lutaiphong

**Comment by rumpl** [comment]
Hey @lutaiphong thanks for opening this issue.

We have identified the problem and are working on a fix.

Cheers

**Comment by glours** [comment]
@lutaiphong the new `3.6.0` version of Docker Desktop with the fix was released yesterday! 
Can you upgrade by clicking on `Check for Updates` and check that everything is working well now?

**Comment by lutaiphong** [comment]
It's worked. Thanks @glours .
