### ISSUE TITLE
Visual Studio Code Insiders Feature Request

### ISSUE THREAD

**Issue by kibblewhite** [docker/dev-environments#3]
Docker Dev Environments to work with Visual Studio Code Insiders - Please, thank you :)

![image](https://user-images.githubusercontent.com/4837916/123263105-e726f500-d4f8-11eb-9bb2-cd5b669e7104.png)

Currently, no workaround that I am aware of.

**Comment by nebuk89** [comment]
@kibblewhite Thanks for opening! Yes we have this on our current sprint so hopefully we will add this in a couple of weeks :)

**Comment by kibblewhite** [comment]
> @kibblewhite Thanks for opening! Yes we have this on our current sprint so hopefully we will add this in a couple of weeks :)

You lot are the best! Thanks team.

**Comment by ZaLiTHkA** [comment]
I discovered this myself earlier today at work (where I run macOS), just wanted to test it at home first (where I run Pop!_OS and Windows 10). for the record, I run VSCode Insiders on all three.

it seems someone beat me to logging this one. 🍻 either way, just a quick note then: this does indeed affect all three OS platforms.

anyways, I second @kibblewhite's sentiments: thank you, these tools you amazing people create are downright awesome.. 😁

**Comment by lmf-git** [comment]
What value does it add?

**Comment by Al-Ferguson** [comment]
> What value does it add?

My VSCode Insiders install has all my Preview & Daily Extensions. This allows my base VSCode install to be a little more stable/predictable while I can flip over and test the latest extensions/fixes if I want/need. As this is still experimental, this is where I would prefer to be running from for the near future.

**Comment by lmf-git** [comment]
I'm really struggling to find a use case for dev environments, there's a big share button and the video that I watched barely demonstrated the main point... any modern dev environment has to be collaborative like that.

I think Vercel is about to kill Docker and VS Code in one hit at this rate.

Please, someone, anyone, demonstrate the magnificence of Docker's dev environments properly.

**Comment by glours** [comment]
VsCode Insiders will be supported in the next release of Docker Desktop!

**Comment by vasilvestre** [comment]
The issue can be closed
