### ISSUE TITLE
Error when launching sample dev environment: "No such image"

### ISSUE THREAD

**Issue by phoenixeliot** [docker/dev-environments#34]
**Describe the bug**
When trying to launch the example "single container dev environment", I receive this error:
```
Error invoking remote method 'dev-envs-backend': Error: {"Message":"Error response from daemon: No such image: docker/dev-environments-go:stable-1"}
```

**To Reproduce**
1. Go to Dev Environments [Preview] for the first time
2. Click on "Single container dev environment" under "Try running a sample"
3. Wait for about 30 seconds for the dev environment container to finish trying to launch itself

**Expected behavior**
I expected not to receive an error, and to be able to use the sample dev environment (I don't know what that would look like exactly, as I haven't used this feature before).

**Screenshots**
<img width="1577" alt="Screen Shot 2021-07-20 at 12 07 44" src="https://user-images.githubusercontent.com/491376/126374242-8800534e-3e91-44b7-94b8-e4403b3c106e.png">

Logs as shown if I click on the row: (doesn't contain anything meaningful)
<img width="1577" alt="Screen Shot 2021-07-20 at 12 11 27" src="https://user-images.githubusercontent.com/491376/126374266-988f9f86-6c0a-4276-9724-c6148b01ec71.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.4, on an M1 macbook air
 - Docker Version 3.5.1 (3.5.1.7)

**Additional context**

After upgrading to Docker Version 3.5.2 (3.5.2.18), I get the same error but in the logs instead of as a banner: 
```
Error response from daemon: No such image: docker/dev-environments-go:stable-1
```
<img width="1382" alt="Screen Shot 2021-07-20 at 12 17 48" src="https://user-images.githubusercontent.com/491376/126375073-54d2b207-74a5-4f5f-8666-e94de247fb9b.png">

I still get the same error if I delete the dev environment and try again.

I also get a different error if I try to use the other sample environment from the "Compose based dev environment" button:
<img width="1382" alt="Screen Shot 2021-07-20 at 12 19 09" src="https://user-images.githubusercontent.com/491376/126375312-7f774c57-273f-445a-ba89-72cd7c9c41dc.png">

**Comment by glours** [comment]
Hello @phoenixeliot 
Can you upload a dignostic (menu `troubleshoot` and the `Get support` button) and then copy the diag number as a comment to this issue? 

After that, you can, as a workaround, download the image directly with the docker CLI
`docker pull docker/dev-environments-go:stable-1` and then retry the dev environment sample

For the issue with the Compose sample, are you using a proxy or a VPN? I'll check in details what happens in the diagnostic.

**Comment by phoenixeliot** [comment]
Welp, the both example images work now. So I may not be able to provide any more useful info, and the problem *might* be solved.

FWIW, I am not behind any kind of VPN or proxy. Using the same network as when I reported this issue (my home wifi).

**Comment by glours** [comment]
Can you check if you're still using the `3.5.1` or if Docker Desktop was updated since the last time?

**Comment by glours** [comment]
Ok good to know. 
Can we close this issue?

**Comment by phoenixeliot** [comment]
Yeah, go ahead.
