### ISSUE TITLE
Custom dev-environment Dockerfile

### ISSUE THREAD

**Issue by andrew-stclair** [docker/dev-environments#36]
**Tell us about your request**
If the git repository has a file, For example `Dockerfile.dev`, use that to build the development environment instead of pulling a pre-made image from docker hub.

**Which service(s) is this request for?**
Docker Desktop Dev Environments

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
While using the pre-made images is fine, it would be nice to be able to pull the necessary requirements during container build instead of installing them later, or to build a lighter container for a lean development environment

**Are you currently working around the issue?**
I have looked into using a normal container do do this, but being able to have docker desktop handle the whole process from pulling code to building the container would simplify the process

**Comment by alantbarlow** [comment]
This is currently solved by using a docker-compose.yaml file located in the .docker directory at the root of the project. The project I am currently working on implements a custom dockerfile. if you want to see how it's set up, you can go to https://github.com/alantbarlow/project-slideshow. In my setup, the dockerfile is named "Dockerfile" (the default) and is located at the root of the project. You'll have to change the "build" value in the docker-compose to specify the path to your dockerfile if it isn't the same.
