### ISSUE TITLE
Facing unknown host prompt when connecting to VPN git server on port 7999

### ISSUE THREAD

**Issue by webark** [docker/dev-environments#37]
When using a custom git server, with an internal custom host, I was unable to move past the "this is an unknown host" prompt. This is from the logs.

```
The authenticity of host '____ (###.###.###.###)' can't be established.
ECDSA key fingerprint is SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
```

**To Reproduce**
1. Go to 'Dev Environnements'
2. Fill create field with internal git server
3. Click on 'Create button'

**Expected behavior**
New unknown hosts to be added automatically, or open a terminal or similar to allow for responding to prompts.

**Desktop (please complete the following information):**
 - OS: Big Sur 11.4
 - Version Docker Desktop 3.5.2

**Comment by glours** [comment]
Did you already or can you try to clone the repository from directly from your machine? 
We use a proxy to pass credentials from the host so you should be able to clone the repository if you already connect from your host to this repository
Did you use a proxy or VPN to access to the git server?
Is your git server configured with a custom port?

**Comment by webark** [comment]
> Did you already or can you try to clone the repository directly from your machine?
What do you mean by this? I can clone it normally. I was not sure how to reference a local git repository
>Did you use a proxy or VPN to access to the git server?
VPN
>Is your git server configured with a custom port?
7999

**Comment by rumpl** [comment]
@webark could you please create and upload a diagnostic via the menu Troubleshoot/Support?

When cloning we are forwarding the `~/.ssh/known_hosts` file inside the container that clones the code but in your setup it might be that the known hosts file is somewhere else.

**Comment by webark** [comment]
@rumpl 

> When cloning we are forwarding the ~/.ssh/known_hosts file inside the container that clones the code but in your setup it might be that the known hosts file is somewhere else.

The host I am trying to connect which it logs out is in the known hosts file. If I exec into the git container it creates, I am able to clone the repo.

> could you please create and upload a diagnostic via the menu Troubleshoot/Support?

I wasn't able to get anything to do this other than it just taking me to the "for-mac" github bug page? I could be doing something wrong/not on a paid teams account.

**Comment by rumpl** [comment]
When you click on "Support" you normally get to this screen, wait a while and you will see a "Upload to get a Diagnostic Id"

<img width="1382" alt="Screenshot 2021-08-10 at 16 59 02" src="https://user-images.githubusercontent.com/99933/128890481-a6d7cabf-b069-4e9f-b733-ff4c03fc8fc8.png">

<img width="1382" alt="Screenshot 2021-08-10 at 17 00 16" src="https://user-images.githubusercontent.com/99933/128890732-078b1c4a-b534-46d3-b905-11dced1e072b.png">

<img width="1382" alt="Screenshot 2021-08-10 at 17 00 54" src="https://user-images.githubusercontent.com/99933/128890826-6d3431c8-3526-44d7-8200-89248d6aae98.png">

<img width="1382" alt="Screenshot 2021-08-10 at 17 01 38" src="https://user-images.githubusercontent.com/99933/128890957-c9ce3e49-3b1d-4863-b879-4bf87cbe1eb3.png">

You can then give us that diagnostics ID and we will take a look at the logs.

**Comment by webark** [comment]
Yea, that's what I tried, and it just hung on the "diagnosing" for 5 mins before I clicked away. I'll let it sit for longer and see if it can resolve.

**Comment by webark** [comment]
@rumpl yea. Left it open for an hour and never got past the `Diagnosing ...` message. Perhaps it's due to the process being hung by waiting for the prompt?

Let me know if there is something I can do or provide to help diagnose. Thanks! :)

**Comment by rumpl** [comment]
Hm. That’s odd, @djs55 any ideas how we can get the diagnostics?

@webark if all else fails it could help us if we could do a quick zoom call when you are available. Hit me an email at djordje.lukic@docker.com if you have the time. I’m on the Paris timezone

**Comment by djs55** [comment]
I would try the command-line to see if it gives any clue about where it's blocking:
```
/Applications/Docker.app/Contents/MacOS/com.docker.diagnose gather -upload
```
Failing that, the most useful logs are in `~/Library/Containers/com.docker.docker/Data/log` -- a good fallback would be to create a .zip of those and send by email.

**Comment by glours** [comment]
@webark we just released `3.6.0` version of Docker Desktop which fix an issue when using a custom port, I didn't guarantee that will fix your problem, but a least you can send us your logs with this new version.
To upgrade just click on the `Check for Updates` menu

**Comment by webark** [comment]
@glours this fixed it!! Thanks so much. Going to be closing this now.

**Comment by shyagamzo** [comment]
The VSCode extension is not recognized for me.

Diag. ID: FA0A526B-5CB0-48F3-B6EF-849DB959D052/20211209095751

![image](https://user-images.githubusercontent.com/95415447/145375930-3f39f39f-8e4a-417a-bf23-1f0f0d09614e.png)

![image](https://user-images.githubusercontent.com/95415447/145375693-d5f93517-5d2b-40a7-88de-8ef36fca7786.png)

Also, there's a strange behavior... When I click the 'Retry' button, VSCode opens in Restricted Mode over some internal VSCode file:
![image](https://user-images.githubusercontent.com/95415447/145376281-f79d2175-a235-4fe4-b9f7-f7d774c7e7d2.png)
