### ISSUE TITLE
Creating a new dev environment from the dockersamples/single-dev-env repository does not recognise Go as main language

### ISSUE THREAD

**Issue by ppluijten** [docker/dev-environments#53]
**Description**
When following the instructions at https://docs.docker.com/desktop/dev-environments/#start-a-single-container-dev-environment, **creating a new Environment** does not recognise **Go** as the main language of the repository and so uses *docker/dev-environments-default* as base image instead of *docker/dev-environments-go*. This means the commands `make` and `go` are not available to run in the container.

**To Reproduce**
1. Go to https://docs.docker.com/desktop/dev-environments/#start-a-single-container-dev-environment
2. Follow the instructions
3. When executing the step `make run`, see the error: **command *make* not available**

**Expected behavior**
The command `make` should be available from the *docker/dev-environments-go* image to run a local webserver hosting at port 80.

**Desktop**
 - OS: Windows 10
 - Version 2004 (19041.1165)

**Version of Docker Desktop:**
![image](https://user-images.githubusercontent.com/975661/130612463-633d211a-b9c9-4f83-884c-2bcdb4ece7c0.png)

**Workaround**
This problem can be resolved by specifying the correct base image, like explained in https://docs.docker.com/desktop/dev-environments/#specify-a-base-image. But as mentioned there, this is not a lasting fix and moreover the docs specify that the langauge should be recognised automatically and I can imagine not everyone will find this workaround.

**Comment by glours** [comment]
@ppluijten can you retry, we added `make` to our base image few weeks ago so you should not have the issue anymore

**Comment by smoms** [comment]
same problem. I have just tried.

**Comment by ppluijten** [comment]
> @ppluijten can you retry, we added `make` to our base image few weeks ago so you should not have the issue anymore

@glours, unfortunately the error message remains the same. I checked and the base image `docker/dev-environments-default:stable-1` is up-to-date. Can you reference the image in which `make` should now be available?

**Comment by glours** [comment]
@ppluijten the issue seems to be on the langage detection, the `dockersamples/single-dev-env` should be detected as a Golang project and should use the `docker/dev-environments-go:stable-1` image as base image
We already opened a ticket in our internal board to fix that

**Comment by glours** [comment]
@ppluijten I just add a workaround directly in the repository of the `single-dev-env` sample, can you try if it fixes your issue please?

**Comment by ppluijten** [comment]
@glours, this seems to fix it for now:
![image](https://user-images.githubusercontent.com/975661/134479328-4f6e7476-caa6-4250-928e-92616a91521a.png)
The `make` command is indeed available after this, thank you for this!
