### ISSUE TITLE
Got 'Error' when trying to specify base image

### ISSUE THREAD

**Issue by balazsgrill** [docker/dev-environments#55]
**Describe the bug**
I tried to specfiy development base image in my repository as described here: https://docs.docker.com/desktop/dev-environments/#specify-a-base-image. When I try to create a dev environment on this (https://github.com/balazsgrill/wscgo@feature/docker-env), I get a single 'Error' message without details.

There might be a problem with my configuration, however IMHO this message should provide more information.

**To Reproduce**
1. Open Docker for Windows
1. Go to 'Dev Environments'
2. Click on 'Create'
3. Select 'Remote Git Repository'
4. Paste 'https://github.com/balazsgrill/wscgo@feature/docker-env'
5. Click Create
6. See error

**Expected behavior**
Dev-env container is created, or a meaningful message is presented

**Screenshots**
![image](https://user-images.githubusercontent.com/611150/131209220-21b1e8c0-79d6-4aeb-9067-64bfa4b278a3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10.0.19043

**Version of Docker Desktop:**  
You can find the version by clicking on the `About Docker Desktop` menu
```
Version: 3.6.0 (67351)
Engine: 20.10.8
```
![image](https://user-images.githubusercontent.com/611150/131209313-cdea73dc-ef6b-4470-8a7f-d3d05c87643e.png)

**Additional context**
I uploaded diagnostics: 793DE4A7-FDA3-42FE-A74A-9A2267C15C09/20210828063408

**Comment by glours** [comment]
Hello @balazsgrill 

It's seems we have issue with branches following the `feature/` pattern, thanks for reporting the issue. 
It should be fix easily

**Comment by glours** [comment]
Hi @balazsgrill 
We just release Docker Desktop `4.0.1`, can you update to this version and check that this issue is fixed now?

**Comment by balazsgrill** [comment]
Hi @glours , I've just tried it and it works great!
Thanks!
