### ISSUE TITLE
Checkout recursive Submodules

### ISSUE THREAD

**Issue by dlanileonardo** [docker/dev-environments#6]
**Tell us about your request**
I think many repositories use submodules to keep microservices organized in compose, and in the main repo of stack link references for each. 

**Which service(s) is this request for?**
Checkout recursive submodules

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Woking of Submodules of repository

**Are you currently working around the issue?**
No

**Additional context**

**Comment by rumpl** [comment]
Hi @dlanileonardo, thanks for opening this issue. We overlooked this, it should be fairly easy to fix. I'll keep you posted.

**Comment by stephanierifai** [comment]
Thanks for bringing this back up @aglsteve! We're taking a look 👀 !

**Comment by MitchellUTS** [comment]
I also would love to see the ability to recursively clone a git repository when creating a dev environment.

This issue has been closed with no reason specified, but the `docker dev create` reference didn't mention for this feature in Docker Desktop 4.23.0 (120376).

Is this feature still planned?
