### ISSUE TITLE
/var/folders/ no such file or directory

### ISSUE THREAD

**Issue by MSzmaj** [docker/dev-environments#73]
**Describe the bug**
When creating a new dev-environment from a private github repo I get the following error:
`could not find /var/folders/bh/pyyk003x5b39k4fqhk2vq5br0000gn/T/volume-appname-vibrant_shamir/appname/var/folders/bh/pyyk003x5b39k4fqhk2vq5br0000gn/T/volume-appname-vibrant_shamir/appname: stat /var/folders/bh/pyyk003x5b39k4fqhk2vq5br0000gn/T/volume-appname-vibrant_shamir/appname/var/folders/bh/pyyk003x5b39k4fqhk2vq5br0000gn/T/volume-appname-vibrant_shamir/appname: no such file or directory
exit status 17`

**To Reproduce**
1. Click 'Create New Environment'
2. Enter git repository (make sure to have the ssh keys added)
3. Get error

**Expected behavior**
New dev-env is set up with the git project.

**Desktop**
 OS: macOS 12.0.1 using M1 Macbook Pro

**Version of Docker Desktop:**  
```
20.10.10, build b485636
```

**Other useful Info**
I've added both /var/folders and /private/var/folders as resources and restarted docker and computer multiple times.

**Comment by glours** [comment]
Hi @MSzmaj 
Thanks for your feedback. 
Does your Git repo contain a compose file a the root directory or in the `.docker` folder? If so it seems there is a different behaviour between Compose V1 and Compose V2, at least, when building images with absolute paths. Internally we're using the `compose-go` library to generate the dedicated compose file to run the Dev Environments and this library generate absolute path. 

So we currently have a workaround which is to turn off the usage of Compose V2 in the Docker Desktop
![compose-v2](https://user-images.githubusercontent.com/705411/141792865-70aeadc5-018c-4476-a6a7-94ee82014696.png)

**Comment by MSzmaj** [comment]
> Hi @MSzmaj Thanks for your feedback. Does your Git repo contain a compose file a the root directory or in the `.docker` folder? If so it seems there is a different behaviour between Compose V1 and Compose V2, at least, when building images with absolute paths. Internally we're using the `compose-go` library to generate the dedicated compose file to run the Dev Environments and this library generate absolute path.
> 
> So we currently have a workaround which is to turn off the usage of Compose V2 in the Docker Desktop ![compose-v2](https://user-images.githubusercontent.com/705411/141792865-70aeadc5-018c-4476-a6a7-94ee82014696.png)

Hi @glours 
Thank you very much. You are absolutely correct. That is the solution. I'll marked this as closed.

**Comment by glours** [comment]
FYI [a fix has been merged](https://github.com/docker/compose/pull/8929) in Compose this morning, so Compose stacks should work with Compose V2 in the next Docker Desktop release
