### ISSUE TITLE
Creating compose based dev environment fails with exit status 17

### ISSUE THREAD

**Issue by strokovnjaka** [docker/dev-environments#74]
**Describe the bug**
Creation of a compose based sample dev env fails with `exit status 17`

**To Reproduce**
1. Open Docker desktop
2. Click on 'Dev Environments' on the left band
3. Click 'Create' (or 'Create New Environment' in case no envs are there yet)
4. Click 'Get started'
5. Select 'NEW DEV ENVIRONMENT' tab
6. Select 'Existing git repo'
6. Put `https://github.com/dockersamples/compose-dev-env` into 'Enter the Git Repository'
7. Click 'Continue'
8. Wait for the error 'exit status 17' to appear

OR, when no dev envs exist

1. Open Docker desktop
2. Click on 'Dev Environments' on the left band
3. Click 'Compose based dev environment' (bottom right)
4. Click 'Get started', then 'Continue'
5. Wait for the error 'exit status 17' to appear

**Expected behavior**
The step '3 Preparing' should pass without errors.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15.7

**Version of Docker Desktop:**  
The `About` menu does nothing, the following version is from 'Preferences/Software Update':
```
Docker Desktop 4.2.0 (70708)
```

**Log of step 3**
```
Error
Unfortunately, something went wrong.

Preparing to clone inside a volume
Installing credential helpers... done
Cloning into '/code'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.remote: Counting objects:  93% (55/59)
remote: Compressing objects: 100% (45/45), done.remote: Compressing objects:  42% (19/45)
remote: Total 59 (delta 17), reused 41 (delta 10), pack-reused 0
Receiving objects: 100% (59/59), 14.33 KiB | 698.00 KiB/s, done.Receiving objects:  93% (55/59)Receiving objects:  83% (49/59)Receiving objects:  54% (32/59)Receiving objects:  50% (30/59)
Resolving deltas: 100% (17/17), done.Resolving deltas: 100% (17/17))Resolving deltas:  52% (9/17)Resolving deltas:  35% (6/17)
Detecting main repo language...
Detected 'Go' as the main repository language.
could not find /var/folders/mv/d6rs2p9j0cjbfsd1r1pykqtc0000gn/T/volume-compose-dev-env-distracted_pare/backend/var/folders/mv/d6rs2p9j0cjbfsd1r1pykqtc0000gn/T/volume-compose-dev-env-distracted_pare/backend: stat /var/folders/mv/d6rs2p9j0cjbfsd1r1pykqtc0000gn/T/volume-compose-dev-env-distracted_pare/backend/var/folders/mv/d6rs2p9j0cjbfsd1r1pykqtc0000gn/T/volume-compose-dev-env-distracted_pare/backend: no such file or directory
exit status 17
```

**Comment by glours** [comment]
Hello @strokovnjaka 

There is a bug in the version of Compose V2 shipped with the last version of Docker Destkop. [A fix has been merged](https://github.com/docker/compose/pull/8929) this morning and should be available in the next version of Docker Desktop.

A workaround is described in the issue #73 (remove the usage of compose v2 in Docker Desktop settings)

We can let this issue open until the next release of Docker Desktop, to let people know how to find the workaround.

**Comment by strokovnjaka** [comment]
Hi @glours, thanks, not sure how I missed the #73.

**Comment by strokovnjaka** [comment]
With `Docker Desktop 4.3.0 (71786)` this works with Compose V2 as well.
