### ISSUE TITLE
single-dev-env always "sleep infinity"

### ISSUE THREAD

**Issue by whybangbang** [docker/dev-environments#75]
![image](https://user-images.githubusercontent.com/8721386/142721847-77133939-8473-4ec7-8ecb-c780cd9f6d01.png)
 
the reason is not set entrypoint?
![image](https://user-images.githubusercontent.com/8721386/142721896-b97c9728-64d0-4077-94c7-3e1058301aee.png)

**Comment by glours** [comment]
Hello @whybangbang 

A Dev Environment container is expected to be connected to an IDE. To let you work as long as you want in your IDEwe should keep the container up and running, that's why we defined `sleep infinity` as the entrypoint of Dev Environment containers. 
Does it make sens for you?

**Comment by whybangbang** [comment]
thx, i get it now
