### ISSUE TITLE
dev-env doesn't work with docker-compose

### ISSUE THREAD

**Issue by Zig1375** [docker/dev-environments#79]
Cannot run VSCode for docker-compose.
I've tried to do that for my own code and for the docker-compose example.  

MacOS 11.5
Docker: 4.3.0 (71786)

Video with the issue:
https://www.dropbox.com/s/m1swztz6sbiiqly/docker.mov?dl=0

**Comment by felipecruz91** [comment]
Hey @Zig1375, could you send us the diagnostics ID? You can see how to get it from the [official documentation](https://docs.docker.com/desktop/windows/troubleshoot/#in-app-diagnostics).

**Comment by Zig1375** [comment]
Hey, 
Here's my diagnostics ID: C941BBAF-46A1-4209-82A5-000DAB955C4B/20211207110253

**Comment by glours** [comment]
@Zig1375 can you try with the `Use Docker Compose V2` unchecked in your Docker Desktop Preferences?
![compose-v2](https://user-images.githubusercontent.com/705411/145672516-61ce9504-e429-43bd-a41f-9be4b71a97cb.png)

**Comment by Zig1375** [comment]
yes, it helped. Thank you.

**Comment by glours** [comment]
@Zig1375 

We just release a new version of Docker Desktop  `4.4.1 `. Now it should work with Compose V2, can you give it a try and let me know if we can close the issue?

**Comment by Zig1375** [comment]
I cannot find the version 4.4.1 . The check for updates shows that I have already had the latest version 4.3.1.  
Once I get the 4.4.1 I'll try it and let you know. 
Thank you

**Comment by glours** [comment]
My bad 🤦‍♂️ , `4.4.1` is an internal preview, but a `4.3.2` will be released soon with the fix

**Comment by Zig1375** [comment]
@glours 
Thank you. It works fine now.
