### ISSUE TITLE
Cannot share environment

### ISSUE THREAD

**Issue by AndrewSav** [docker/dev-environments#87]
**Describe the bug**

Sharing is not working 

**To Reproduce**
Steps to reproduce the behaviour:

Try to share the environment as per screenshots below

**Expected behaviour**
I expect the environment to be shared

**Screenshots**
![2021-12-30_13-56-26](https://user-images.githubusercontent.com/658865/147713420-0c47fe93-5bc3-498d-b60c-1d55a8fb1ad9.png)
![2021-12-30_13-57-33](https://user-images.githubusercontent.com/658865/147713465-61b2843a-40f1-4312-9bfa-e6b053a12cdf.png)
![2021-12-30_13-58-26](https://user-images.githubusercontent.com/658865/147713493-fb4489bb-4d8e-4d6c-b009-61216aab1883.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Version of Docker Desktop:**  
```
4.3.2 (72729)
```

**Comment by felipecruz91** [comment]
Hi @AndrewSav, thanks for reporting the issue.

To help us identify the problem, could you provide the diagnostics ID? here are the instructions on how to do this: https://docs.docker.com/desktop/windows/troubleshoot/#diagnose-and-feedback

**Comment by AndrewSav** [comment]
@felipecruz91 E3D4977B-457B-422D-B272-05699C9A8262/20220111212157

**Comment by felipecruz91** [comment]
Thanks for the diagnostics ID, @AndrewSav.

After some investigation, we believe it has to do with the name of the GitHub repo you're creating the Dev Environment from. Can you try renaming your repository in GitHub from `Memento` to `memento` (all lowercase)? Then, try creating the Dev Environment again.

Could you confirm if that works? If so, we have a fix ready to be released.

**Comment by AndrewSav** [comment]
@felipecruz91 nope, I also tried it on your own repo `dev-environments` with the exactlly same result. I'm also showing the repo on screenshots (now deleted) that is all lowercase. so this is not the reason.

**Comment by frankcorneliusmartin** [comment]
I encounter the same issue: 
![image](https://user-images.githubusercontent.com/15981243/154928694-fa28e46b-8501-4af6-ae02-1644e9024137.png)

**Comment by AndrewSav** [comment]
It appears that even with the full system info and logs that are uploaded to get the diagnostics ID the issue is too hard to track down. On the other hand it's preview still, so there is hope that it can be made functional before the release.

**Comment by glours** [comment]
Hello there,

The issue was detected and a fix is currently in review.

**Comment by glours** [comment]
@AndrewSav the fix has been ship with Docker Desktop `4.7.0`.
Do you still have the issue?

**Comment by AndrewSav** [comment]
Nope, just checking that there is nothing outstanding from your side. Thanks!

**Comment by andrewwerling** [comment]
The share button is not even available to me... is there something i'm missing?

**Comment by ccarbonellbh** [comment]
Same issue for me. The button is nowhere to be found
